### ISSUE TITLE
Smalrubyの準備

### ISSUE THREAD

**Issue by vestige** [TochigiRaspberryPICircle/kit#1]
* Mac, ラズパイともインストール失敗
* 会社のwindowsはインストール、実行まで完了
* この後の選択肢
   * 誰かのwindowsにインストールするか？
   * Rubyのコードが出力できるところまでするか...
   * 別のにするか

**Comment by mame-n** [comment]
この前、toRubyで見た時は、限定かもしれないけど動いていたよね。

**Comment by vestige** [comment]
そですねー。できれば実際にうごいてるとこまでみせたいですねー

**Comment by naominix** [comment]
Smalrubyですが、

Raspberry Pi 3(NOOBS2.1.0のRaspbian）
Ruby2.2.2(rbenv)

で動作しました。

Ruby2.4.0ではNGでした。

**Comment by vestige** [comment]
おー、ありがとうございます！
このあと、無事にねこさん、うごきました？

**Comment by naominix** [comment]
はい。ネコさんも他のキャラも動きました。

**Comment by vestige** [comment]
おー、よいですねー。
なんで自分のだめなんだろう...
もう一度チャレンジしてみます。

**Comment by vestige** [comment]
@naominix さんはこの手順でやったのでしょうか？

https://docs.google.com/document/d/1USIWn9YUdRqiquAgOXx_tkWhrZA48brqxZ-HmVFX_Kg/mobilebasic

**Comment by naominix** [comment]
この文書は初めて見ましたが、やった手順的には近い気がします。

**Comment by vestige** [comment]
僕のはmacでやっても、ラズパイでやっても同じようなエラーになってしまうんですよね。
dxruby_sdlが正常にインストールされてないような感じがするんですよね...

**Comment by naominix** [comment]
dxruby_sdlは割りとすんなり入った記憶が(^-^;;

**Comment by vestige** [comment]
インストールはすんなりなのですが、実際に動かすと動かないので、困っている感じなのですー。

**Comment by naominix** [comment]
なるほど。どんなエラーが出るのでしょうか。

**Comment by vestige** [comment]
あ、いま入れ直して見てるので、またエラーでたら貼ってみますー。

**Comment by vestige** [comment]
https://github.com/TochigiRaspberryPICircle/kit/blob/master/screenshot/0205.jpg

**Comment by naominix** [comment]
なんと、起動後に出るんですね（驚）。
これは出ないでちゃんとネコも他のキャラも動いていますね・・・。
何が違うんだろう・・・

**Comment by vestige** [comment]
そなんですよ。なにかSDLまわりでインストールをしくじってるんですかね。よくわからないんですー。

**Comment by naominix** [comment]
もう一度、NOOBS2.1.0を焼き直して最初からやり直してみました。

教えていただいたドキュメント
https://docs.google.com/document/d/1USIWn9YUdRqiquAgOXx_tkWhrZA48brqxZ-HmVFX_Kg/mobilebasic?usp=gmail

の以下の部分だけ飛ばしてセットアップを実施しました（以下の部分は以前もやった記憶が無かったためです）

----飛ばした手順----
LXTerminalを起動して、
$ update_rubygems
$ gem update
→(H27.9現在で、2.0.0-p353ではrakeとrdocの上書きは「N」を選択。2.2.2ではプロンプトが出ない)
$ rbenv rehash
☆dxruby_sdlのインストール
----飛ばした手順----

その結果、問題なく動作しました。
Audio周りの設定は特にいじっていないのでデフォルトのままですね（HDMI出力になっている状態です）。
ブロックを移動してはめる時のカチって音がなるのでここが動くかどうかが問題になっているのかもしれませんね。

**Comment by vestige** [comment]
まっさらからインストールしなおして動くようになりました。
おそらくpythonでゲームライブラリを使った時にインストールしたライブラリのどれかが問題だったみたい。
依存がおおくて複雑すぎる...
