### ISSUE TITLE
ロボット戦車の進捗について

### ISSUE THREAD

**Issue by vestige** [TochigiRaspberryPICircle/kit#14]
進捗をかいたり、次の作戦を載せたりします。

みんなが参照しそうなメモはここにまとめていきたいです

- https://github.com/TochigiRaspberryPICircle/kit/wiki/ロボット戦車

**Comment by vestige** [comment]
あるといいかも？

http://akizukidenshi.com/catalog/g/gC-04351/
http://akizukidenshi.com/catalog/g/gP-02681/

**Comment by vestige** [comment]
# 2017.10
- モーターとブレッブボードをつける

**Comment by vestige** [comment]
* モータードライバー
* http://windvoice.hatenablog.jp/entry/2016/01/16/220541

**Comment by vestige** [comment]
webiopiのインストールをした

**Comment by vestige** [comment]
このページをみて、設定してみることにする。
https://github.com/TochigiRaspberryPICircle/kit/wiki/ラズパイでScratch2動かす

**Comment by vestige** [comment]
次回はもう一度、戦車自体のハウジングについて見直す
はんだごても使うかも？

**Comment by vestige** [comment]
菅沼さんバージョンをコミットした

https://github.com/TochigiRaspberryPICircle/kit/tree/master/tank/ctrl_webiopi

**Comment by fleg949** [comment]
↓こんなキットが出てました＾＾　高っ
『親子で電子工作入門 ラズパイとスマホでラジコン戦車を作ろう！』　工作キット　ST-TANK-KIT-N 
https://www.amazon.co.jp/dp/B06XRVYFKH/ref=sspa_dk_detail_0?psc=1

**Comment by akimach** [comment]
@fleg949 学生にはつらいです。実際はいくらぐらいで買えるものなのでしょうか。

**Comment by vestige** [comment]
スマホもついてたら、安いかもねー

**Comment by fleg949** [comment]
構成が個々で異なるので、一概には言えませんが、
2000円～　かと思いますが、皆さんいかがでしょう？

タミヤ 特別企画商品 透明 ユニバーサルプレートセット 2枚セット 69906 ￥347 
タミヤ 楽しい工作シリーズ No.100 トラック&ホイールセット (70100) ￥468
タミヤ 楽しい工作シリーズ No.168 ダブルギヤボックス 左右独立4速タイプ (70168) ￥615

あとは、ご家庭にある
小型のブレッドボードやモータードライバー
モーター駆動用の電池ケース
ラズパイ稼働用の小型モバイルバッテリ
などが必要と思います。

**Comment by vestige** [comment]
ひとまず、あるところまで進んだので一度クローズします
