### ISSUE TITLE
プログラミングデー in 上辺見小

### ISSUE THREAD

**Issue by vestige** [TochigiRaspberryPICircle/kit#18]
# 日時
- 2017/10/28(sat) 9:45-11:45

# 場所
- 〒306-0234 茨城県古河市上辺見１１６４　上辺見小学校
   - 児童クラブ（東側）教室

## アクセス：
- 車　今泉地域コミュニティセンターから、新4号経由で、約53km
    - 駐車場 : 学校に数台分と、少し歩きますが、複数台止められる場所があります。
- 電車　JR古河駅下車、徒歩3km、　バス　上辺見停留所下車徒歩1分

# 内容
いまのところ、下記ワークショップとＳＴＥＭ教材展示を考えてます。（学校側と調整中）

## ワークショップ（体験会）
- タブレットを使ってプログラミングを体験してみよう
   - https://code.org/minecraft
   - Hour of Code　https://code.org/learn

- パソコンやタブレットを使わずに、体験してみよう
   - ＣＳアンプラグド：ルビィのぼうけん、テラと７人の賢者

- ボール型ロボットを使ってプログラミングを体験してみよう
   - Sphero SPAK+	

## ＳＴＥＭ教材
- Sphero SPARK+
- mBot
- GLICODE　ほか

**Comment by vestige** [comment]
まずは手伝ってくれる人はここで表明してもらえればよいのかな？

**Comment by fleg949** [comment]
はい、まずは当日、来ていただける方の人数を知りたいです。

場所：
　〒306-0234 茨城県古河市上辺見１１６４　上辺見小学校

アクセス：
車　今泉地域コミュニティセンターから、新4号経由で、約53km
電車　JR古河駅下車、徒歩3km、　バス　上辺見停留所下車徒歩1分

**Comment by vestige** [comment]
駐車場はあるのですか？

**Comment by fleg949** [comment]
駐車場あります。
学校に数台分と、少し歩きますが、複数台止められる場所があります。

**Comment by fleg949** [comment]
いまのところ、下記ワークショップと
ＳＴＥＭ教材展示を考えてます。（学校側と調整中）

■ワークショップ（体験会）
・タブレットを使ってプログラミングを体験してみよう
	　https://code.org/minecraft
　　　Hour of Code　https://code.org/learn
・パソコンやタブレットを使わずに、体験してみよう
	ＣＳアンプラグド：ルビィのぼうけん、テラと７人の賢者
・ボール型ロボットを使ってプログラミングを体験してみよう
	Sphero SPAK+	

■ＳＴＥＭ教材
・Sphero SPARK+
・mBot
・GLICODE　ほか

**Comment by fishburger** [comment]
今日、高田さんからこちらのお話しをききました。
上辺見小学校以外の子供の参加も大丈夫でしょうか。
大丈夫でしたらうちの子供もつれて参加（お手伝い）させてください。

**Comment by vestige** [comment]
大丈夫ですよー

**Comment by vestige** [comment]
て、僕が答えてもよかったんだろうか笑
来週中にコンパスでスタッフの人数確認用のサイトを用意しますね。

**Comment by fishburger** [comment]
ありがとうございます。

**Comment by fleg949** [comment]
大丈夫ですよ～
出来れば、来週水曜日までに、だいたいの人数
を把握したいですが、 いかがでしょうか？
今のところ、四名さんぐらいですかね

**Comment by fleg949** [comment]
大丈夫ですよ～
出来れば、来週水曜日までに、だいたいの人数
を把握したいですが、 いかがでしょうか？
今のところ、四名さんぐらいですかね

**Comment by vestige** [comment]
https://torpc.connpass.com/event/68479/

**Comment by vestige** [comment]
とりあえず、上に登録してもらうと連絡しやすいかもー

**Comment by mame-n** [comment]
せっかくの機会ですけど、都合がつけられません。
またぜひ、お声をかけてください!!

**Comment by naominix** [comment]
応援に行きたいですが、スケジュールが重なっているため行けないので、また別の機会がありましたらその時にお願いします。

**Comment by fleg949** [comment]
mame-nさん、naominixさん　
ご連絡ありがとうございます。お気持ちだけでもとてもうれしいです。

**Comment by kotatuneco** [comment]
fleg949 さん、私の知り合いでぜひ参加（お手伝い）したい方がいるのですが、よろしいでしょうか？

**Comment by vestige** [comment]
@fleg949 @kotatuneco たぶん大丈夫だと思いますよ。連絡とかが周知することがあるかもしれないので、上のコンパスから登録だけはしてもらった方がよいかもー。

**Comment by kotatuneco** [comment]
@vestige コンパスに登録するよう伝えておきます。

**Comment by fleg949** [comment]
ありがとうございます。

資料を、後ほど送ります。

**Comment by oogakim** [comment]
@vestige @fleg949 10/28行けそうなのでconnpassには登録しました。
当日の集合時間と、それまでに何か準備できること教えて欲しいです。
何ができるかわからないので見学程度になりそうですけど。

**Comment by fleg949** [comment]
OGAKIさん
ありがとうございます。

先程Facebookのほうへ、情報を送りました。

わからないことあれば、遠慮なく問い合わせください。

/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
高井 和之
E-Mail ： fleg949@gmail.com
携帯電話 ： 080-8912-6621
/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/

2017年10月24日 19:48 Masaki OGAKI <notifications@github.com>:

**Comment by fleg949** [comment]
今日は、遠くまで来ていただき、
本当にありがとうございました。

忘れ物が、いくつかありましたので、
次回お会いしたときお渡しします。

あと、バタバタしていて、
写真をとるのを忘れて
しまったんですが、
どなたか、子供たちの写真あります
でしょうか？

**Comment by vestige** [comment]
無事におわったのでクローズ

記事のリンクを載せておきます。

http://ict-enews.net/2017/10/31kamihemi/
