### ISSUE TITLE
宇都宮大学での子供向けイベント

### ISSUE THREAD

**Issue by vestige** [TochigiRaspberryPICircle/kit#19]
# タイトル
- まだない？

# 概要
- @akimach が主催予定　
- 来年ぐらいに

**Comment by akimach** [comment]
@TochigiRaspberryPICircle/tropic 
とりあえず開催できる体制と場所はあるので、何かやりたいなーというのが今の段階です。これからまとめて行きたいと思います。

**Comment by akimach** [comment]
# TensorFlow勉強会 2017年9月24日での話し合い

プログラミング教育の百花繚乱ぶりを体感した。

* [GLICODE®](http://cp.glico.jp/glicode/)
* [コンピュータサイエンスアンプラグド](http://csunplugged.jp/)
* [Micro:Bit](http://microbit.org/ja/)
* [MinecraftのHour of Codeチュートリアル](https://code.org/minecraft]
* 坂村健によるコンピュータを使わないコンピュータ教育（トランプとか使う）
* [mBot](https://www.kenis.co.jp/mbot/)
* etc

「教材やデバイスどうするか問題」で上がった声

* ラズパイだとOSのセットアップが手間
* Arduinoだとそういう手間がない
* micro:Bitもラクらしい
* コードをかかせるのか？
* やはりScratchか

**Comment by vestige** [comment]
1月には具体的な話をはじめたい。

**Comment by akimach** [comment]
@vestige 
分かりました。9月の開催を目指したいと思っています。

**Comment by akimach** [comment]
#33 で話すので閉めます。
