### ISSUE TITLE
Scratch Day 2017 in 那須町までの交通手段について

### ISSUE THREAD

**Issue by vestige** [TochigiRaspberryPICircle/kit#2]
乗り合わせとか必要だったりするかな？

**Comment by vestige** [comment]
いまのところわかっていることを整理します

- 高井さん→前日入り、現地集合

- 中内さん→当日、現地集合

- 僕のクルマ→当日、宇都宮から乗り合わせで行く予定
　　- 木村くん
　　- 菅沼さん

あとは、
いなみさん( @inamihiroyuki )と、くじらいさん（ @fishburger  ）はどうしますか？

**Comment by fishburger** [comment]
すいません！出遅れました！
私は当日に車で現地入りします。
もし同乗されたい方がいたら教えて下さい。

あと、事前の準備とか、当日の役割はもう決まっている感じでしょうか？

**Comment by vestige** [comment]
りょうかいです。
当日の役割はまだないですー。
事前準備については別スレッドでたてておきますね。

**Comment by vestige** [comment]
いなみさんも自分の車でくると連絡あったので、これはおしまい。
