### ISSUE TITLE
2018年度夏休みこどもプログラミング教室@宇大

### ISSUE THREAD

**Issue by akimach** [TochigiRaspberryPICircle/kit#33]
この前、 @vestige さんと話した内容です。

* 候補日：8/5?、~9/15, 9/22~
* 定員：20名（=親子10組程度）
* 内容：プログラミングのワークショップ
  * ScratchとRasPi
  * 栃Piメンバーによる発表会・デモ
* 時間：13:00 〜 16:00
* 対象：小学生全学年とその保護者
* 会場：宇都宮大学
* 備考：
  * 宇都宮市の学校に広報予定
  * PCは10台程度貸出可能
  * 学生は3、4人程度お手伝い予定

**Comment by akimach** [comment]
以上の内容で、昨日に提出しました。

**Comment by vestige** [comment]
ありがとう。次の勉強会で説明しようと思います。
ていうか、8/5だとやっぱりあまり時間なさそうだねー^^;

**Comment by akimach** [comment]
@vestige 
@vestige 

> 普段の活動報告、またはこの勉強会を通してやりたいことをこの場で発表しあうようなことをしたいです。

はい。前回お話したとおり、プログラミング教室の構成や流れについては、よねざわさんはじめとちぎラズパイ勉強会のみなさんにお任せしたいと思います。

**Comment by akimach** [comment]
> #30 をベースにすこし掘り下げられたら

PCは貸出できます。ラズパイはないので難しいですね

**Comment by akimach** [comment]
@vestige 

聞いてみますが、ほぼ確定だと思います。

**Comment by akimach** [comment]
唐突なご提案でわちゃわちゃしてしまい、申し訳ございません。今後、冬休み、春休みなどにも開けたらなーと思うので前向きに検討していただけるとありがたいです。

負担を軽くするためにいくつか策は施せると思うので、ぜひ言ってください。

* 前半は僕を含め学生でプログラミング教室の構成を考えて実施、後半にラズパイ勉強会のみなさんが発表会
* もう少し時間を短くして、シンプルにする

などなど

いずれにせよ話し合わないといけませんね。

**Comment by fleg949** [comment]
もしよければですが、
さくらや近隣のCoderDojoに、
声かけてみて良いですか

先日ScratchDay in NASUのように
都合が合えば、水戸やひたちなかから
も来てくれるかもです。

2018年6月8日(金) 11:22 Akimasa KIMURA <notifications@github.com>:

**Comment by akimach** [comment]
@fleg949 @vestige 

> さくらや近隣のCoderDojoに、
> 声かけてみて良いですか

ありがとうございます。ココらへんで話は留めておいて、よねざわさんがおっしゃるようにまずは次回のラズパイ勉強会で話し合ったほうがよいかと思います。会場の規模的にも大規模にやることは難しいですし

**Comment by vestige** [comment]
今日、 @mame-n さんと話した。話した中から自分のメモをのこしておく

　
- すでにあるコンテンツをやるのはよい
- はじめに完成品を見せる。お絵かきを自由に
- 子供中心、大人中心？
- ラズパイ はいくつ用意できるか？
- キーボード、マウス、モニターも必要。用意できるか？
- 感想（ワールドカフェ）は子供が飽きてしまいそう
- ２ターンにして、ロボットアンテナからなにか追加できないか？センサーっぽいのとか？

**Comment by akimach** [comment]
@vestige 

ありがとうございます。確認してみます。

> 9月ぐらいでもいいのでは？夏休みの土曜日は予定合わせにくい？

附属小学校などにも連絡はしますし、これは広報次第だと思います。

**Comment by akimach** [comment]
いろいろとアイディアはあって、考えうる変数が多くなってしまうので

* 8/5開催
* mac book pro 10台程度貸出（マウスもおそらく大丈夫です）
* 数名学生のお手伝い可能

という制約条件のなかで、まずやれそうなことを探れたらなーと思ってます。

**Comment by vestige** [comment]
https://github.com/TochigiRaspberryPICircle/kit/wiki/programmingEventTorpc

**Comment by vestige** [comment]
きになること（7/1）

- wifiはどうなる？
- OSを揃えたSDカードを用意した方がいい？
- モニター、キーボード、マウスはあった方がいい
- 配線のケーブル、抵抗

**Comment by vestige** [comment]
https://torpc.connpass.com/event/93290/

**Comment by akimach** [comment]
> wifiはどうなる？

用意できない可能性がありますが、確認してみます。

> OSを揃えたSDカードを用意した方がいい？

Rasbianのバージョンで差はないと思うので、最近のものであれば大丈夫ではないかと思われます。

> モニター、キーボード、マウスはあった方がいい

米澤さんに個別に連絡します。

> 配線のケーブル、抵抗

こちらでご用意するのは難しいと思います。

**Comment by vestige** [comment]
スタッフだけでまずはいくつラズベリーパイあるか確認だね。
GUI使うのでラズパイ3がいいような気がする。
2のB+でも大丈夫かなぁ？

**Comment by kotatuneco** [comment]
貸し出せる機材について連絡します。
・Pi3 x 2台
・Pi3B+ x 1台
・PC用ディスプレイ x 2台

**Comment by vestige** [comment]
@kotatuneco ありがとうーございますー。

**Comment by akimach** [comment]
ご用意できる機材：

・Pi3B+ x 1台
・PC用ディスプレイ x 3台以上
・マウス x 3台
・キーボード x 3台

**Comment by vestige** [comment]
@akimach @fleg949 ありがとうございます。

**Comment by vestige** [comment]
2ターン目をタクトスイッチでと考えていたけど、よく考えたらブレッブボード使わない予定だった。
センサーは困りそうだよね、どうしようかなぁ。

**Comment by mame-n** [comment]
予習したいのですが、やろうとしているロボットの参考Webとかありますか?
タクトもそうですが、試しにLEDやる場合もブレッドボード便利ですよね。かき集めますか。
でもブレッドなしのLEDだとワニ口クリップとか使おうと思っていた?

**Comment by vestige** [comment]
@mame-n 
https://projects.raspberrypi.org/en/projects/robot-antenna
参考にしようとしてるのは上のサイトです。
メス-メスのジャンパーワイヤーは用意してありますよ

**Comment by vestige** [comment]
あと、参加者が定員になったそうですー。
なので、機材とかを再確認しないとだ

**Comment by vestige** [comment]
一応、現状の持ち物をまとめて見た。ちょっと機材足りない。どうしようか。

https://github.com/TochigiRaspberryPICircle/kit/wiki/programmingEventTorpc#用意するもの

**Comment by naominix** [comment]
PiServer
https://tech.nikkeibp.co.jp/atcl/nxt/column/18/00079/00004/

でThinクライアント運用できるでしょうか。
若干不安もありますが・・・

**Comment by vestige** [comment]
@naominix ありがとうござまいます。もしかすると、お声掛けさせてもらうかもです。ThinClientもあるんですね。まぁありますよね。GPIOを使うのでこっちはちょっとだめそうかもですー。

**Comment by akimach** [comment]
[続き](https://github.com/TochigiRaspberryPICircle/kit/issues/33#issuecomment-406230343)：

* Pi3：1台追加

ボランティアとして参加予定の学生のものです。

**Comment by rohatodenirou** [comment]
私もお手伝いします。

・Pi3 x 2台
・PC用ディスプレイ x 2台
・マウス x 2台
・キーボード x 2台

**Comment by vestige** [comment]
@rohatodenirou ありがとうございます！
ディスプレイ、キーボード、マウスは大丈夫そうなのですが、ラズパイ の電源、HDMIのケーブルがたりなそうなのでその辺を記述してもらえるとうれしいですー

それと、２ターン目のをつくってみました。このぐらいなら、どうかな？
https://scratch.mit.edu/projects/237011851/

**Comment by vestige** [comment]
りんご動かしてみるバージョン
https://scratch.mit.edu/projects/237012531/

**Comment by vestige** [comment]
mameさんのもはっておくー
https://scratch.mit.edu/projects/237022181/

**Comment by mame-n** [comment]
星野さん
文面が寝ぼけていました。

ラズパイをお借りする件ですが、やはりこちらで十分に用意できないので3台ほどお借りしたいと考えています。
せっかくですからB+をお願いできますか。
23日の受講の時に妻に渡していただくのが都合がいいのですが、いかがでしょう。
ちなみにお借りするラズパイ用の電源ケーブルはお持ちでしょうか。あればそれもお借りしたいのですが。

米澤さん、昨日の話では3台借りると記憶していますが正しいですか。

**Comment by vestige** [comment]
@mame-n 昨日、星野さんに連絡しておきました。ごめんなさい。一緒にいれておけばよかった。３台借りる話はしてありますよ。

**Comment by naominix** [comment]
@mame-n さん、3B+3台用意しておきます。電源（3A出力×２、2A出力×１ですが、月曜日までに新しい3A出力が届けば全部3Aになります）も３つ用意します。

**Comment by mame-n** [comment]
了解です。では23日、お願いします。

**Comment by rohatodenirou** [comment]
下記用意できます。
HDMIケーブル x 2
3A電源 x 2
2.5A電源 x 2
coderdojo sakuraで使ってるwifi(42台同時接続可能)も借りられると思いますが、どうしますか？

**Comment by vestige** [comment]
@rohatodenirou  wifiはいまのところ必要ないので大丈夫ですよ。ありがとうございます。

**Comment by vestige** [comment]
HDMIで接続できるモニターが２台たりないので、もってこれる人はもってきて欲しいですー。
僕は１台もっていきます。
@kotatuneco さん、もってこれます？

**Comment by vestige** [comment]
作りかけだけど、こういう感じで用意してみてるところです

https://drive.google.com/open?id=143xMlKXmPltiOTmbKHqmZfzh5bRoK18u

**Comment by akimach** [comment]
@vestige それか、HDMI オス to VGAメスのケーブルがあればOKです。

**Comment by kotatuneco** [comment]
@vestige 
了解しました。
モニタ持参します。

**Comment by akimach** [comment]
当日の駐車場所についての連絡です。北側のゲートから入ってください。

午前中にスタッフ用に10組、午後に参加者10組分の駐車することを伝えておきました。

![image](https://user-images.githubusercontent.com/17570265/43138204-12043962-8f89-11e8-8e37-f15c94fa0a52.png)

**Comment by akimach** [comment]
補足です。9:30〜14:00まで北ゲートを開けてもらっています。出るのは自由です。

**Comment by vestige** [comment]
いろいろ、書き直してみました。ちょっと冗長になったかも...
あと、CM用の説明文ほしいですー。

https://drive.google.com/open?id=143xMlKXmPltiOTmbKHqmZfzh5bRoK18u

**Comment by mame-n** [comment]
https://www.instagram.com/p/BllIX2QBSNg/?taken-by=mame_shou
これの問題は、
1. ロボットにつける時、大きな穴を開けて裏から付けるしかできない
2. 手持ちの抵抗が1/6Wとリードが細いので、ブレッドボード・ジャンパーワイヤのメスに挿してもブカブカ
1は裏からつけてもらう、2は1/4Wを米澤さんに買ってきてもらう、でしょうか。
制作上や耐久性の問題はなさそうです。

**Comment by mame-n** [comment]
CM用の説明文に那須ラボがあるの、星野さんはご存知かな?

**Comment by naominix** [comment]
3Aアダプタお渡しする際にチラシをお渡ししたいと思います

**Comment by vestige** [comment]
1/4wの抵抗かいましたー。
あと、 @fleg949 @rohatodenirou さん、資料くださいー。
那須ラボの件はりょうかいです。

**Comment by fleg949** [comment]
@vestige 遅くなってごめんなさ～い。Messenngerで送りました。宜しくお願いします<m(__)m>

**Comment by rohatodenirou** [comment]
@vestige 遅くなりすみません。情報送りました。よろしくです。

**Comment by vestige** [comment]
いろんな人にレビューしてもらって、いちおうこんな感じになりました

https://drive.google.com/open?id=143xMlKXmPltiOTmbKHqmZfzh5bRoK18u

**Comment by akimach** [comment]
「HDMI対応」のディスプレイはありますが、HDMIケーブルはないっス。

一度、みなさんのHDMIケーブルの持参の有無を確認しておいたほうがいいと思います。

**Comment by vestige** [comment]
@akimach 

何本たりないのかな？
モニターたりない話もあったから確認できてないと思うけど。

**Comment by fleg949** [comment]
https://drive.google.com/open?id=143xMlKXmPltiOTmbKHqmZfzh5bRoK18u
宣伝ありがとうございます。

一点、
「CoderDojo」が正しい表記となるので、
スペースなしでお願いします。m(_ _)m
https://coderdojo.jp/docs/brand-guidelines

**Comment by akimach** [comment]
@vestige 10本ないです。

**Comment by vestige** [comment]
当日のレイアウト

![paper 5](https://user-images.githubusercontent.com/555286/43402531-eacc7e30-944d-11e8-9256-cfd3c713fd78.png)

**Comment by mame-n** [comment]
HDMIはA-Aが2本、A-C変換が1つあるよ。必要なら動作確認するけど。

**Comment by vestige** [comment]
@mame-n  一応、１０本そろいましたが、念のためもってきてくださいー

**Comment by mame-n** [comment]
Foodはお菓子を持っていけるかも。Drinkはコップとか用意しますか?

**Comment by akimach** [comment]
RASPBIAN STRETCH WITH DESKTOP(June 2018)のmicroSDカードへの書き込みを5枚分やりました。動作確認も「Welcome to the Raspberry Pi Desktop!」のウィンドウが表示されるまでやりました。

**Comment by vestige** [comment]
@akimach 
おつかれさま、ありがとう。
あと、机の配置、どう思う？
それと、参加者へのメールはいつ頃おくるのかな？

**Comment by akimach** [comment]
コンセントはラズパイに1つ、ディスプレイに1つ必要なので、20個は必要です。電源タップも確認しておきましょう。

**Comment by akimach** [comment]
きになってることなのですが、今回の勉強会で怪我とか想定はできなくはないじゃないですか？そこあたりの管理はどうしますか？

みなさんのほうが詳しいのだと思うのですが、Lチカといえど、正統派の電子工作を教えるなら手袋も用意するべきかと。

**Comment by mame-n** [comment]
私は電子工作を子供とやったことはないです。
今回は親御さんがついているので、親御さん向けの注意を徹底する、くらいかな。
プレゼン資料か配布資料があれば免責記載はやっておいていいかも。

先が尖っているので、手に刺す、目に入れてしまう等々が考えられます。
感電は大丈夫と思いますが、GPIO全ピンOFFするスクリプトをデスクトップに置いておいて、いつもダブルクリックさせるというのはどうですか。

**Comment by akimach** [comment]
[続き](https://github.com/TochigiRaspberryPICircle/kit/issues/33#issuecomment-409215447)

怪我は想定しているとのことなので、よねざわさんとご相談して免責掲載はしないということになりました。お騒がせしてしまい申し訳ございませんでした。

ただ、[スライド](https://drive.google.com/file/d/143xMlKXmPltiOTmbKHqmZfzh5bRoK18u/view)からはそういった配慮はあまり分からないので、掲載したほうがよいと思うのですが、いかがでしょうか。

**Comment by vestige** [comment]
こういうのを足しますよ。大人な対応してもらいたいですが、トラブルになったときにみんなが困るのはいやなので。

![info](https://user-images.githubusercontent.com/555286/43517467-c5888cfa-95c3-11e8-9f2c-696941a8dd3b.png)

**Comment by vestige** [comment]
トラブル上の問題だから、病む上ないのかもしれないけど、やっぱりあんまり納得いかないなー。
これはそういう類のイベントだったのかなー？
だから、親を同席にしたんだけど。
言い訳みたいな感じがして、自分がもし親子でやるような時にこれ言われると、こいつら無責任なー、って思っちゃうのはひねくれてるのかな？
先の細いものを扱うから注意が必要は入れるのは納得しましたー。
これ、自分むいてないねー

**Comment by vestige** [comment]
このイベントは宇都宮大学とも関係ないとか入れないとこのイベントのあと文句言われちゃうのかな？

**Comment by akimach** [comment]
@vestige 「免責事項」という言葉に拒否反応を示しているようですが、そこまで大げさに受け取られる必要はないかと思います。それに[免責掲載](https://github.com/TochigiRaspberryPICircle/kit/issues/33#issuecomment-409534431)は入れないはずではないでしょうか。それよりは、LEDの先っちょは危ないので気をつけましょうとか入れてほしかった。[上](https://github.com/TochigiRaspberryPICircle/kit/issues/33#issuecomment-409215447)で一番良いたかったのは、怪我しそうなところの共有ですし、免責掲載とかコンプライアンスとかは二の次です。

**Comment by mame-n** [comment]
私は免責部分を入れないでも構いません。
もし小さくても、例えばハサミやリードで血が出たとき、GPIOショートで煙が上がった時にスタッフはどうすればいいかを考えておきませんか。米澤さんの感覚もわかります。ので、私の提案、後半の責任云々は削除でいいと思いました。

**Comment by vestige** [comment]
@wbydo よろしくおねがいしますー♩

えっと、いろいろあったけど、話をすると、
当日のスタッフが集合した時点でどこにみんなが気をつけないところをもう一度確認したいと思います。
また、中内さんがあげてくれたようにトラブルがおきたときにどういう風にするかも話したいと思います。
当日は、集合したら以下のことをやろうと思っています

ースタッフが気にしておくことを確認
ー事故が起きたときの行動の確認
ーイベントの時間割を確認
ースタッフの配置
ーテーブル配置
ー足りないものを買い出し（絆創膏、テーブルタップ、養生テープ、USBケーブル、電源）
ーラズパイ のセットアップ

**Comment by mame-n** [comment]
工作用の抵抗付きLEDを作ってみました。赤4、緑5、黄5。

https://drive.google.com/file/d/1I-zC122zRXkqwkkk1e2ndd5DoJ0V6ExB/view?usp=sharing

ところで、当日、抵抗を変えて明るさが変わることとかやるんですか?
残LEDは米澤さんの小さいのが10個あります。そこに100Ω、10kΩの抵抗をつけてみました。
写真じゃわかりにくいですが、10kΩでも暗く光ってます。ただなかなか難しいです。米澤さんのLEDはリード線が細いので、ジャンパ線のメスに刺しても簡単に抜けてしまいますね。
ちなみに10kは手持ちで10個あります。

[100Ω](https://drive.google.com/file/d/1vSTtH_FP7P1-bbOGP2Umy6WmssUqAqVi/view?usp=sharing)
[10kΩ](https://drive.google.com/file/d/127X4g4B6XkzmFIOZhqs3T72rZcqQbWPE/view?usp=sharing)

**Comment by mame-n** [comment]
ゴミ袋、持参します。
当日の様子、写真をブログアップ可能かな?

会計はどうしますか。SDカードとか終わった後、どうする予定?
作ったLED、使い勝手いいので私が買い取ってもいいけど。

**Comment by vestige** [comment]
@mame-n 
抵抗変えるなはやらないです。説明しないといけないので。
会計などはあまり考えてなかったです。当日のイベント終了後にやりましょう。
問題なければ欲しい人がいれば、参加者にあげたいところだけど。
写真については参加者に確認した方がいいかも。一枚スライド用意しておきます。
