### ISSUE TITLE
プログラミングデー in 那須町 6月23日版

### ISSUE THREAD

**Issue by mame-n** [TochigiRaspberryPICircle/kit#34]
急ですが、6月23日に開催されるプログラミングデー in 那須町の告知を兼ねたissueを立てさせてください。
いつもの那須町系イベントですが、今回は子供が300人越えだそうで、かなりの賑わいになると予想されます。
お手伝い兼子供とガジェット+プログラミングで参加いただけそうな方は nakauchi.s@gmail.comにメイルをいただけませんか。
ちなみに私は参加できませんが、高井さんが参加予定です。

**Comment by vestige** [comment]
おわったからクローズ
