### ISSUE TITLE
マルチバイブレーター

### ISSUE THREAD

**Issue by vestige** [TochigiRaspberryPICircle/kit#38]
実験するのに必要なものをかいておく
あと、参考になりそうなものをはっておく

https://www.nicovideo.jp/watch/sm13109978

https://www.qoosky.io/techs/12cc544eea

**Comment by vestige** [comment]
無安定マルチバイブレーターって言ってたね。

トランジスタ x2   (2SC1825Y)
LED x2
抵抗器 x 4
電解コンデンサー x2

**Comment by mame-n** [comment]
1825? あまり聞かないけど、あってます?

**Comment by mame-n** [comment]
気づかなかったと思うけど
https://www.instagram.com/p/BmqbmWrB6lf/?taken-by=mame_shou
が、メーカーフェアで買ったマルチバイブレーターキットだよ。

**Comment by vestige** [comment]
まちがってた！トランジスタ。なおしたー

**Comment by vestige** [comment]
メーカーフェアでかったやつ今度持ってきてくださいー
