### ISSUE TITLE
通知系の実験会をしたい

### ISSUE THREAD

**Issue by vestige** [TochigiRaspberryPICircle/kit#42]
* やってみたいこと
   * ラズパイからの通知（スマホへ）
   * ラズパイへの通知（スマホから）

* こんな技術を組み合わせてみる
   *  IFFT
   * Node-RED  
   * Webhook

* 参考サイト
   * https://qiita.com/minatomirai21/items/4c4e777b43ede1e42900

**Comment by vestige** [comment]
https://nodered.jp/docs/hardware/raspberrypi

**Comment by kotatuneco** [comment]
https://qiita.com/undo0530/items/95dc85e3b58380ea359a
