### ISSUE TITLE
Node-REDの勉強

### ISSUE THREAD

**Issue by vestige** [TochigiRaspberryPICircle/kit#46]
この本いいんじゃないかな？

https://www.amazon.co.jp/ブラウザでお絵描きI-Node-REDで極楽コンピュータ・プログラミング-インターフェースSPECIAL-桑野-雅彦/dp/4789849317/ref=sr_1_1?__mk_ja_JP=カタカナ&keywords=NOde-red&qid=1558831075&s=gateway&sr=8-1

**Comment by kotatuneco** [comment]
その本、持ってます。

本日持って行きますよ。
