### ISSUE TITLE
Scratchできね子オマージュに挑戦する。

### ISSUE THREAD

**Issue by mame-n** [TochigiRaspberryPICircle/kit#5]
レトロゲームオマージュシリーズ第二弾をScratchデーをターゲットに作成する。
前作、サーカスのコードをきれいにして、2作を展示したい!!

きね子とは
https://ja.wikipedia.org/wiki/%E3%82%AD%E3%83%8D%E3%83%86%E3%82%A3%E3%83%83%E3%82%AF%E3%82%B3%E3%83%8D%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3

- 2x2、4x4まで
- 動画は4つくらい完成させたい
- 動画はコスチューム切り替えですます
- 実装は大変じゃないけど、動画作るのがものすっごく手間かかる
- 動画作りを誰かにやってほしい。

**Comment by vestige** [comment]
動画大変そう

**Comment by naominix** [comment]
Animated GIFを用意してスプライト画像として読み込むと各コマがコスチュームで分離されるのでそれを活用するとデータが作りやすいかもしれません。
元動画→Animated GIF→Scratchスプライト

**Comment by mame-n** [comment]
おぉ、それはいいですね。基板実装終わったら見てみます。

**Comment by mame-n** [comment]
あれでよければ一旦クローズしようかと思います。
あとは出来高で。
