### ISSUE TITLE
Please update https://github.com/TochigiRaspberryPICircle/kit/wiki/MakeRaspiHat

### ISSUE THREAD

**Issue by sethhillbrand** [TochigiRaspberryPICircle/kit#54]
The site `kicad-pcb.org` is no longer controlled by the KiCad project

https://forum.kicad.info/t/warning-avoid-all-links-to-kicad-pcb-org-use-kicad-org/31521

**Comment by sethhillbrand** [comment]
Also at https://github.com/TochigiRaspberryPICircle/kit/wiki/takata

**Comment by kotaproj** [comment]
Thank you.
I have edited the link.
