### ISSUE TITLE
はんだごて勉強会

### ISSUE THREAD

**Issue by vestige** [TochigiRaspberryPICircle/kit#6]
おすすめのはんだごて教えてー

**Comment by kotatuneco** [comment]
下記に記載しておきました。
https://github.com/TochigiRaspberryPICircle/kit/wiki/%E3%81%AF%E3%82%93%E3%81%A0%E3%81%94%E3%81%A6%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

**Comment by vestige** [comment]
ありがとうございますー 🤗

**Comment by vestige** [comment]
勉強会が無事におわったのでクローズ
