### ISSUE TITLE
会場情報、スタッフ情報について

### ISSUE THREAD

**Issue by vestige** [TochigiRaspberryPICircle/kit#9]
あとでかく

- 会場で飲食可能なのか？

- 場所が変わった
   - 那須町文化センター
   - http://www.town.nasu.lg.jp/hp/page000000500/hpg000000432.htm

- スタッフ情報

- お昼の話

- タイムテーブル

**Comment by vestige** [comment]
ここのページに書いていこうと思いますー
https://github.com/TochigiRaspberryPICircle/kit/wiki/ScratchDay2017

**Comment by naominix** [comment]
＞会場で飲食可能なのか？

小ホールは不可です。
楽屋はOKだそうです。

**Comment by fishburger** [comment]
乗り合わせの件ですが、私は自分の車で行くことにします。
